version: '3'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    entrypoint: sh -c "echo 'CREATE DATABASE IF NOT EXISTS dev; CREATE DATABASE IF NOT EXISTS test;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql/data:/var/lib/mysql
